server:
  port: 9090
spring:
  banner:
    location: classpath:banner.txt
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1111
    url: jdbc:mysql://localhost:3306/mango?serverTimezone=UTC

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
