server:
  port: 9090
spring:
  banner:
    location: classpath:banner.txt
  druid:
    url: jdbc:mysql://192.168.91.133:3306/mango?serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 1111

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.mjf.mango.manggoadmin.mapper: debug

log:
  path: mango-logs
